# Generated by Django 3.0.3 on 2020-07-26 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(editable=False, unique=True)),
                ('nickname', models.CharField(db_index=True, max_length=128)),
                ('is_hide', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
                'db_table': 'profiles',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(editable=False, max_length=24)),
                ('type', models.CharField(choices=[('int', 'integer'), ('pct', 'percent')], default='int', editable=False, max_length=3)),
                ('value', models.IntegerField(default=0, editable=False)),
                ('custom_value', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'score',
                'verbose_name_plural': 'scoring',
                'db_table': 'scoring',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64)),
                ('log_name', models.CharField(editable=False, max_length=64, unique=True)),
                ('cls_base', models.CharField(blank=True, choices=[('aircraft', 'aircraft'), ('ammo', 'ammo'), ('block', 'block'), ('crew', 'crew'), ('turret', 'turret'), ('vehicle', 'vehicle')], max_length=24)),
                ('cls', models.CharField(blank=True, choices=[('aaa_heavy', 'aaa_heavy'), ('aaa_light', 'aaa_light'), ('aaa_mg', 'aaa_mg'), ('aerostat', 'aerostat'), ('aircraft_gunner', 'aircraft_gunner'), ('aircraft_heavy', 'aircraft_heavy'), ('aircraft_light', 'aircraft_light'), ('aircraft_medium', 'aircraft_medium'), ('aircraft_pilot', 'aircraft_pilot'), ('aircraft_static', 'aircraft_static'), ('aircraft_transport', 'aircraft_transport'), ('aircraft_turret', 'aircraft_turret'), ('armoured_vehicle', 'armoured_vehicle'), ('artillery_field', 'artillery_field'), ('artillery_howitzer', 'artillery_howitzer'), ('artillery_rocket', 'artillery_rocket'), ('block', 'block'), ('bomb', 'bomb'), ('building_big', 'building_big'), ('building_medium', 'building_medium'), ('building_small', 'building_small'), ('bullet', 'bullet'), ('car', 'car'), ('driver', 'driver'), ('explosion', 'explosion'), ('locomotive', 'locomotive'), ('machine_gunner', 'machine_gunner'), ('parachute', 'parachute'), ('rocket', 'rocket'), ('searchlight', 'searchlight'), ('ship', 'ship'), ('ship_heavy', 'ship_heavy'), ('ship_light', 'ship_light'), ('ship_medium', 'ship_medium'), ('shell', 'shell'), ('tank_heavy', 'tank_heavy'), ('tank_light', 'tank_light'), ('tank_medium', 'tank_medium'), ('tank_driver', 'tank_driver'), ('tank_turret', 'tank_turret'), ('trash', 'trash'), ('truck', 'truck'), ('vehicle_crew', 'vehicle_crew'), ('vehicle_static', 'vehicle_static'), ('vehicle_turret', 'vehicle_turret'), ('wagon', 'wagon')], max_length=24)),
                ('is_playable', models.BooleanField(default=False, editable=False)),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Score')),
            ],
            options={
                'verbose_name': 'object',
                'verbose_name_plural': 'objects',
                'db_table': 'objects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('pilot', 'pilot'), ('gunner', 'gunner'), ('tankman', 'tankman')], db_index=True, default='pilot', max_length=8)),
                ('date_first_sortie', models.DateTimeField(null=True)),
                ('date_last_sortie', models.DateTimeField(null=True)),
                ('date_last_combat', models.DateTimeField(null=True)),
                ('score', models.BigIntegerField(db_index=True, default=0)),
                ('rating', models.BigIntegerField(db_index=True, default=0)),
                ('ratio', models.FloatField(default=1)),
                ('sorties_total', models.IntegerField(default=0)),
                ('flight_time', models.BigIntegerField(db_index=True, default=0)),
                ('accuracy', models.FloatField(db_index=True, default=0)),
                ('streak_current', models.IntegerField(db_index=True, default=0)),
                ('streak_max', models.IntegerField(default=0)),
                ('score_streak_current', models.IntegerField(db_index=True, default=0)),
                ('score_streak_max', models.IntegerField(default=0)),
                ('streak_ground_current', models.IntegerField(db_index=True, default=0)),
                ('streak_ground_max', models.IntegerField(default=0)),
                ('sorties_streak_current', models.IntegerField(default=0)),
                ('sorties_streak_max', models.IntegerField(default=0)),
                ('ft_streak_current', models.IntegerField(default=0)),
                ('ft_streak_max', models.IntegerField(default=0)),
                ('sortie_max_ak', models.IntegerField(default=0)),
                ('sortie_max_gk', models.IntegerField(default=0)),
                ('lost_aircraft_current', models.IntegerField(default=0)),
                ('bailout', models.IntegerField(default=0)),
                ('wounded', models.IntegerField(default=0)),
                ('dead', models.IntegerField(default=0)),
                ('captured', models.IntegerField(default=0)),
                ('relive', models.IntegerField(default=0)),
                ('takeoff', models.IntegerField(default=0)),
                ('landed', models.IntegerField(default=0)),
                ('ditched', models.IntegerField(default=0)),
                ('crashed', models.IntegerField(default=0)),
                ('in_flight', models.IntegerField(default=0)),
                ('shotdown', models.IntegerField(default=0)),
                ('respawn', models.IntegerField(default=0)),
                ('disco', models.IntegerField(default=0)),
                ('ak_total', models.IntegerField(db_index=True, default=0)),
                ('ak_assist', models.IntegerField(default=0)),
                ('gk_total', models.IntegerField(db_index=True, default=0)),
                ('fak_total', models.IntegerField(default=0)),
                ('fgk_total', models.IntegerField(default=0)),
                ('ce', models.FloatField(default=0)),
                ('kd', models.FloatField(db_index=True, default=0)),
                ('kl', models.FloatField(default=0)),
                ('ks', models.FloatField(default=0)),
                ('khr', models.FloatField(db_index=True, default=0)),
                ('gkd', models.FloatField(default=0)),
                ('gkl', models.FloatField(default=0)),
                ('gks', models.FloatField(default=0)),
                ('gkhr', models.FloatField(default=0)),
                ('wl', models.FloatField(default=0)),
                ('elo', models.FloatField(default=1000)),
                ('fairplay', models.IntegerField(default=100)),
                ('fairplay_time', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='data.Profile')),
            ],
            options={
                'db_table': 'players',
                'ordering': ['-id'],
                'unique_together': {('profile', 'type')},
            },
        ),
    ]
