# Generated by Django 3.0.3 on 2020-08-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_object_player_profile_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('miss_log_id', models.IntegerField(db_index=True, default=0)),
                ('is_processed', models.BooleanField(default=False, editable=False)),
            ],
        ),
    ]
