# Generated by Django 3.0.3 on 2020-08-08 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_mission_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=256)),
                ('date_start', models.DateTimeField(db_index=True)),
                ('date_end', models.DateTimeField()),
                ('duration', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sortie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=128)),
                ('date_start', models.DateTimeField(blank=True, null=True)),
                ('date_end', models.DateTimeField(blank=True, null=True)),
                ('flight_time', models.IntegerField(default=0)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Mission')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorties_list', to='data.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Mission_Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Mission')),
                ('sorties', models.ManyToManyField(to='data.Sortie')),
            ],
        ),
    ]
